// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm0dfcaH2VAylHpwf5sQLkqjESBhect9o',
    appId: '1:928479886244:web:3c181b04aac73ee0c11f31',
    messagingSenderId: '928479886244',
    projectId: 'qrian-2abf7',
    authDomain: 'qrian-2abf7.firebaseapp.com',
    storageBucket: 'qrian-2abf7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB80zh1L2UMqurHOS251cWvNv4TYdf5w3k',
    appId: '1:928479886244:android:95780b7da31e3436c11f31',
    messagingSenderId: '928479886244',
    projectId: 'qrian-2abf7',
    storageBucket: 'qrian-2abf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtDNrxNlhsIjdz96dV2PZKq2oZR1win_c',
    appId: '1:928479886244:ios:5139a60f4c17be6cc11f31',
    messagingSenderId: '928479886244',
    projectId: 'qrian-2abf7',
    storageBucket: 'qrian-2abf7.appspot.com',
    iosBundleId: 'com.example.qrian',
  );
}
